concurrent = 4
check_interval = 0

[[runners]]
  name = "azure-dragon"
  url = "https://gitlab.${infra.domain}"
  token = "${infra.gitlab.runner.token}"
  limit = 0
  executor = "shell"
  builds_dir = "C:\\gitlab-runner-data\\builds"
  cache_dir = "C:\\gitlab-runner-data\\cache"