concurrent = 4
check_interval = 0

[[runners]]
  name = "vermillion-bird"
  url = "https://gitlab.${infra.domain}"
  token = "${infra.gitlab.runner.token}"
  limit = 0
  executor = "docker"
  builds_dir = "/media/builds"
  cache_dir = "/media/cache"