domain: infra.local
ip: 192.168.0.150

optional:
  dns: yes
  fs: yes

fs:
  server: 10.10.10.10
  root: infra

services:
  gitlab-runner:
    token: TOKEN

machines:
  linux:
    cpus: 2
    memory: 4096
  # windows:
  #   cpus: 2
  #   memory: 4096