version: '3.4'

networks:
  infra_network:
    external: true

volumes:
  gitlab_runner_lin_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab-runner/lin/config"
  gitlab_runner_lin_cache:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab-runner/lin/cache"

  gitlab_runner_win_config:
    driver: local
  gitlab_runner_win:
    driver: local
    #driver_opts:
    #  type: nfs4
    #  o: "addr=${INFRA_FS_SERVER}"
    #  device: ":/${INFRA_FS_ROOT}/gitlab-runner/win"

configs:
  config.toml:
    file: "${INFRA_DIR}/config/config.toml"
