version: '3.4'

# See https://gitlab.com/gitlab-org/gitlab-runner/issues/4295

services:
  gitlab_runner_win_dind_registrator:
    image: gitlab-runner-dind:1809
    command: ["register",
      "--non-interactive",
      "--url", "infra_gitlab",
      "--registration-token", "${INFRA_GITLAB_RUNNER_TOKEN}",
      "--executor", "shell",
      "--shell", "powershell",
      "--description", "black-tortoise",
      "--tag-list", "windows,dind",
      "--locked=false"]
    volumes:
      - gitlab_runner_win_dind_config:C:\Users\build_user\:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.platform.os == windows

  gitlab_runner_win_dind:
    image: gitlab-runner-dind:1809
    volumes:
      - type: npipe
        source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
      - gitlab_runner_win_dind_config:C:\Users\build_user\:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == windows
