version: '3.4'

services:    
  gitlab_runner_win:
    image: win1809-gitlab-runner
    # image: mcr.microsoft.com/windows/nanoserver:1809
    # image: patsissons/gitlab-runner-windows:develop
    # volumes:
    #   - gitlab_runner_win:C:\Gitlab-Runner\
    configs:
      - source: "config.toml"
        target: "C:\\config.toml"
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.platform.os == windows