version: "3.4"

services:
  gitlab_runner_registrator:
    image: gitlab/gitlab-runner:alpine
    command:
      [
        "register",
        "--non-interactive",
        "--url",
        "http://gitlab.${INFRA_DOMAIN}",
        "--registration-token",
        "${INFRA_GITLAB_RUNNER_TOKEN}",
        "--executor",
        "docker",
        "--docker-image",
        "docker:stable",
        "--docker-privileged",
        "--docker-volumes",
        "/var/run/docker.sock:/var/run/docker.sock",
        "--description",
        "vermillion-bird",
        "--tag-list",
        "docker,linux,dind",
        "--locked=false",
      ]
    volumes:
      - gitlab_runner_lin_config:/etc/gitlab-runner:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.platform.os == linux

  gitlab_runner_lin:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_lin_config:/etc/gitlab-runner:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
