version: '3.4'

services:
  gitlab_runner_win_registrator:
    image: gitlab-runner:1809
    command: ["register",
      "--non-interactive",
      "--url", "http://infra_gitlab",
      "--registration-token", "${INFRA_GITLAB_RUNNER_TOKEN}",
      "--executor", "docker-windows",
      "--docker-image", "mcr.microsoft.com/windows/servercore:1809",
      # Windows does not support privileged mode
      # "--docker-privileged",
      # See https://gitlab.com/gitlab-org/gitlab-runner/issues/4295
      # "--docker-volumes", "\\\\.\\pipe\\docker_engine:\\\\.\\pipe\\docker_engine",
      "--description", "azure-dragon",
      "--tag-list", "docker,windows",
      "--locked=false"]
    volumes:
      - gitlab_runner_win_config:C:\Users\build_user\:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.platform.os == windows

  gitlab_runner_win:
    image: gitlab-runner:1809
    volumes:
      - type: npipe
        source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
      - gitlab_runner_win_config:C:\Users\build_user\:z
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == windows