FROM gitlab-runner-base:1809

LABEL maintainer="Alexandr Timofeev <alexandr.p.timofeev@gmail.com>"

SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]

ENTRYPOINT ["gitlab-runner.exe"]
CMD ["run"]
