logLevel = "INFO"
[traefikLog]
filePath = "/var/log/traefik/traefik.log"
[accessLog]
filePath = "/var/log/traefik/access.log"

defaultEntryPoints = ["https","http"]
insecureSkipVerify = true
[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/certs/infra.crt"
        keyFile = "/certs/infra.key"

[api]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "${INFRA_DOMAIN}"
network = "infra_network"
exposedByDefault = false
watch = true
swarmMode = true

[retry]
attempts = 30

[respondingTimeouts]
readTimeout = "360s"
writeTimeout = "360s"
idleTimeout = "360s"

[forwardingTimeouts]
dialTimeout = "360s"
responseHeaderTimeout = "360s"