version: '3.4'

services:
  gitlab:
    image: "gitlab/gitlab-ce:11.1.1-ce.0"
    container_name: gitlab_compose
    volumes:
      - "${INFRA_DIR}/config/gitlab.rb:/etc/gitlab/gitlab.rb:ro"
      - "gitlab_common_data:/var/opt/gitlab"
      - "gitlab_data:/media"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_config:/etc/gitlab"
  redis:
    image: "redis:alpine"
    volumes:
      - "redis_data:/data"
  # postgres:
  #   image: "postgres:9.6-alpine"
  #   volumes:
  #     - "postgres_data:/data"
  #   environment:
  #     POSTGRES_USER: gitlab
  #     POSTGRES_PASSWORD: gitlab
  #     PGDATA: /data
  #     POSTGRES_DB: gitlab

volumes:
  gitlab_common_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/common_data"
  gitlab_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/data"
  gitlab_logs:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/logs"
  gitlab_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/config"
  redis_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: :/${INFRA_FS_ROOT}/redis
  # postgres_data:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: "addr=${INFRA_FS_SERVER}"
  #     device: :/${INFRA_FS_ROOT}/postgres