version: "3.5"

services:
  gitlab:
    image: "gitlab/gitlab-ce:16.1.2-ce.0"
    container_name: gitlab_compose
    networks:
      - infra_network
    volumes:
      - ${INFRA_DIR}/config/gitlab.rb:/etc/gitlab/gitlab.rb:ro
      - gitlab_data:/var/opt/gitlab
      - gitlab_storage:/media
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab

networks:
  infra_network:
    external: true

volumes:
  gitlab_storage:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/storage"
  gitlab_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/data"
  gitlab_logs:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/logs"
  gitlab_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/gitlab/config"
  redis_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: :/${INFRA_FS_ROOT}/redis
  # postgres_data:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: "addr=${INFRA_FS_SERVER}"
  #     device: :/${INFRA_FS_ROOT}/postgres
