version: "3.5"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:latest
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - artifactory_storage:/media
    #  - ${INFRA_DIR}/config/artifactory/system.yaml:/opt/jfrog/artifactory/var/etc/system.yaml
    #  - ${INFRA_DIR}/config/binarystore.xml:/etc/artifactory/binarystore.xml
    configs:
      - source: "artifactory-system.yaml"
        target: "/var/opt/jfrog/artifactory/var/etc/system.yaml"
        mode: 777
    #   - source: "artifactory.config.xml"
    #     target: "/var/opt/jfrog/artifactory/etc/artifactory.config.xml"
    #     mode: 777
    #   - source: "binarystore.xml"
    #     target: "/var/opt/jfrog/artifactory/etc/binarystore.xml"
    #     mode: 777
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        traefik.enable: "true"
        traefik.port: 8082
        traefik.frontend.rule: "Host:artifactory.${INFRA_DOMAIN}"

volumes:
  artifactory_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/artifactory/data"
  artifactory_storage:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/artifactory/storage"
configs:
  artifactory-system.yaml:
    file: "${INFRA_DIR}/config/artifactory/system.yaml"
#   binarystore.xml:
#     file: "${INFRA_DIR}/config/binarystore.xml"
#   artifactory.config.xml:
#     file: "${INFRA_DIR}/config/artifactory.config.xml"
