version: "3.4"

services:
  pypi:
    image: pypiserver/pypiserver:latest
    volumes:
      - pypi_packages:/data/packages
    configs:
      - source: ".htpasswd"
        target: "/data/.htpasswd"
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        traefik.enable: "true"
        traefik.port: 80
        traefik.frontend.rule: "Host:pypi.${INFRA_DOMAIN}"

volumes:
  pypi_packages:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=${INFRA_FS_SERVER}"
      device: ":/${INFRA_FS_ROOT}/pypi/packages"
