version: '3.4'

services:
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infra_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.platform.os == linux
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.port: 8080
        traefik.frontend.rule: "Host:${INFRA_DOMAIN}"