#!/bin/sh

echo "infra: Regenerate Taiga environment..."

set -o allexport && source ${INFRA_DIR}/scripts/taiga-conf.sh && set +o allexport

OUTPUT_FILE="${INFRA_DIR}/config/taiga.env"
touch ${OUTPUT_FILE}

echo "TAIGA_SCHEME=${TAIGA_SCHEME}" > ${OUTPUT_FILE}
echo "TAIGA_DOMAIN=${TAIGA_DOMAIN}" >> ${OUTPUT_FILE}
echo "TAIGA_URL=${TAIGA_SCHEME}://${TAIGA_DOMAIN}" >> ${OUTPUT_FILE}
echo "TAIGA_SITES_SCHEME=${TAIGA_SCHEME}" >> ${OUTPUT_FILE}
echo "TAIGA_SITES_DOMAIN=${TAIGA_DOMAIN}" >> ${OUTPUT_FILE}
echo "SUBPATH=${SUBPATH}" >> ${OUTPUT_FILE}
echo "TAIGA_SUBPATH=${SUBPATH}" >> ${OUTPUT_FILE}
echo "WEBSOCKETS_SCHEME=${WEBSOCKETS_SCHEME}" >> ${OUTPUT_FILE}
echo "TAIGA_WEBSOCKETS_URL="${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"" >> ${OUTPUT_FILE}
echo "SECRET_KEY=${SECRET_KEY}" >> ${OUTPUT_FILE}
echo "TAIGA_SECRET_KEY=${SECRET_KEY}" >> ${OUTPUT_FILE}
echo "POSTGRES_USER=${POSTGRES_USER}" >> ${OUTPUT_FILE}
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> ${OUTPUT_FILE}
echo "EMAIL_BACKEND_TYPE=${EMAIL_BACKEND_TYPE}" >> ${OUTPUT_FILE}
echo "EMAIL_BACKEND=django.core.mail.backends.${EMAIL_BACKEND_TYPE}.EmailBackend" >> ${OUTPUT_FILE}
echo "EMAIL_HOST=${EMAIL_HOST}" >> ${OUTPUT_FILE}
echo "EMAIL_PORT=${EMAIL_PORT}" >> ${OUTPUT_FILE}
echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> ${OUTPUT_FILE}
echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> ${OUTPUT_FILE}
echo "EMAIL_DEFAULT_FROM=${EMAIL_DEFAULT_FROM}" >> ${OUTPUT_FILE}
echo "DEFAULT_FROM_EMAIL=${EMAIL_DEFAULT_FROM}" >> ${OUTPUT_FILE}
echo "EMAIL_USE_TLS=${EMAIL_USE_TLS}" >> ${OUTPUT_FILE}
echo "EMAIL_USE_SSL=${EMAIL_USE_SSL}" >> ${OUTPUT_FILE}
echo "RABBITMQ_USER=${RABBITMQ_USER}" >> ${OUTPUT_FILE}
echo "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}" >> ${OUTPUT_FILE}
echo "RABBITMQ_PASS=${RABBITMQ_PASS}" >> ${OUTPUT_FILE}
echo "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}" >> ${OUTPUT_FILE}
echo "RABBITMQ_VHOST=${RABBITMQ_VHOST}" >> ${OUTPUT_FILE}
echo "RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}" >> ${OUTPUT_FILE}
echo "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}" >> ${OUTPUT_FILE}
echo "ATTACHMENTS_MAX_AGE=${ATTACHMENTS_MAX_AGE}" >> ${OUTPUT_FILE}
echo "MAX_AGE=${ATTACHMENTS_MAX_AGE}" >> ${OUTPUT_FILE}
echo "ENABLE_TELEMETRY=${ENABLE_TELEMETRY}" >> ${OUTPUT_FILE}
